### ISSUE TITLE
After update to 1.0... how to install previous versions?

### ISSUE THREAD

**Issue by evmimagina** [Azure/application-gateway-kubernetes-ingress#669]
Dear AGIC developers team,

I wouldn't say it's a bug, but it's a major change that makes that what it was already working, stopped working. The thing is, after updating the AGIC to the 1.0 version I receive the following error;

".... App Gateway SKU Tier WAF is not supported by AGIC version 1.0.0"

**To Reproduce**
Deploy a WAF v1.
Install AGIC.

It used to work pretty well with the previous version; ingress-azure:0.10.0

I understand that maybe du major changes it's not compatible anymore, but, how could I specifically install the desired previous and working version?

The documentation refers to the following  commands in order to install AGIC;

"
…
helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
helm repo update
wget https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/sample-helm-config.yaml -O helm-config.yaml
…
"

And I can't figure out how to call an installation with a previous reléase version.

Thanks in advance,

**Comment by akshaysngupta** [comment]
Thanks a lot for reaching out. Please refer the following document:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/helm-upgrade.md#rollback

**Comment by evmimagina** [comment]
Hi Akshay,

thanks for your reply. I've found that guide but it references as upgrade and not a clean install... anyway, I've figured it out, just specifying the --version <value> when installing for first time.
BTW, with the latest version of helm (3.0.0), nothing works.

Regards,

**Comment by akshaysngupta** [comment]
We have merged the fix but haven't created release for the helm 3 issue.
Try using helm install with `--set appgw.usePrivateIP=false`
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/664#issuecomment-554239281

**Comment by VipinAgarwal** [comment]
This still doesn't works. I have helm 3 with AGIC chart to set to pull 1.2.0-rc2

 App Gateway SKU Tier Standard is not supported by AGIC version 1.2.0-rc2/082bf0ff/2020-05-19-16:09T+0000; (v0.10.0 supports App Gwy v1)

**Comment by akshaysngupta** [comment]
@VipinAgarwal As the message states, App Gateway V1 SKU is not supported by AGIC version > 0.10.0

**Comment by VipinAgarwal** [comment]
I have tried with all the version of Application gateway (standard, Standard_v2, WAF). All the version had the same error. So I am not sure what is the supported version here?
