### ISSUE TITLE
AGIC with HTTPS Not Fully Creating 

### ISSUE THREAD

**Issue by adamcarter81** [Azure/application-gateway-kubernetes-ingress#851]
I am using AGIC with Istio which is fine over HTTP, but now I want to implement HTTPS to run alongside HTTP.
I have configured TLS passthrough in my Istio service with relevant wildcard certificate, I can test locally by forwarding a port and modifying my hosts file to point the domain to localhost - this works fine with no cert errors.
The issue is when I deploy Agic with what I think is a correct configuration - the front end listener and rules are not created
The backend pool, health probe and http settings are created OK

**To Reproduce**
`apiVersion: v1
kind: Service
metadata:
  name: agic-ingress-https
spec:
  selector:
    #app: istio-ingressgateway.istio-system.svc.cluster.local
    #app: istio-ingressgateway.istio-system
    app: istio-ingressgateway
    #app: azure-vote-front
    #host: istio-ingressgateway
  ports:
  - port: 443
    protocol: TCP
    name: https-443
    targetPort: 443

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #name: istio-ingressgateway-voting
  name: agic-ingress-https
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-hostname: "appgw.domain.com"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "istio-system-wildcard-domain.com"
spec:
  tls:
    - hosts:
      - server.domain.com
      secretName: wildcard-domain-com
  rules:
  - host: server.domain.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: agic-ingress-https
          servicePort: 443`

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> .
`Name:           ingress-azure-7c85c7cfb6-k9qw2
Namespace:      default
Priority:       0
Node:           aks-linux-35064155-vmss000001/15.0.0.35
Start Time:     Mon, 11 May 2020 14:31:19 +0100
Labels:         aadpodidbinding=ingress-azure
                app=ingress-azure
                pod-template-hash=7c85c7cfb6
                release=ingress-azure
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             15.0.0.48
IPs:            <none>
Controlled By:  ReplicaSet/ingress-azure-7c85c7cfb6
Containers:
  ingress-azure:
    Container ID:   docker://8334f6893fe398a1b6d8b4e74ceeed80229db1d905e040fd671a2f522b33d12f
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:2e4cf9def17542533e79f26572183b8ac7bc1b95d39b0c469f11864ca2c99e21
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 11 May 2020 21:36:03 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 11 May 2020 21:34:41 +0100
      Finished:     Mon, 11 May 2020 21:34:41 +0100
    Ready:          True
    Restart Count:  11
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingress-azure-7c85c7cfb6-k9qw2 (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-b66w7 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-token-b66w7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-b66w7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>`

* Output of `kubectl logs <ingress controller>. 
`ERROR: logging before flag.Parse: I0512 09:23:34.068129       1 main.go:306] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0512 09:23:34.109609       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0512 09:23:34.109721       1 main.go:149] App Gateway Details: Subscription: d3af426f-de5c-48ea-a5e8-f645a6ac85e9, Resource Group: rg-aks-lab, Name: ApplicationGateway1
I0512 09:23:34.109732       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I0512 09:23:34.109953       1 httpserver.go:57] Starting API Server on :8123
I0512 09:23:34.243779       1 main.go:191] Ingress Controller will observe all namespaces.
I0512 09:23:34.279388       1 context.go:129] k8s context run started
I0512 09:23:34.279415       1 context.go:168] Waiting for initial cache sync
I0512 09:23:34.579573       1 context.go:176] Initial cache sync done
I0512 09:23:34.579595       1 context.go:177] k8s context run finished
I0512 09:23:34.579658       1 worker.go:35] Worker started
I0512 09:23:34.813381       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
PS C:\repos\aks-lab-001> kubectl logs ingress-azure-7c85c7cfb6-k9qw2
ERROR: logging before flag.Parse: I0512 09:23:34.068129       1 main.go:306] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0512 09:23:34.109609       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0512 09:23:34.109721       1 main.go:149] App Gateway Details: Subscription: d3af426f-de5c-48ea-a5e8-f645a6ac85e9, Resource Group: rg-aks-lab, Name: ApplicationGateway1
I0512 09:23:34.109732       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I0512 09:23:34.109953       1 httpserver.go:57] Starting API Server on :8123
I0512 09:23:34.243779       1 main.go:191] Ingress Controller will observe all namespaces.
I0512 09:23:34.279388       1 context.go:129] k8s context run started
I0512 09:23:34.279415       1 context.go:168] Waiting for initial cache sync
I0512 09:23:34.579573       1 context.go:176] Initial cache sync done
I0512 09:23:34.579595       1 context.go:177] k8s context run finished
I0512 09:23:34.579658       1 worker.go:35] Worker started
I0512 09:23:34.813381       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0512 09:23:55.407952       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.594550007s
I0512 09:23:55.408031       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0512 09:23:55.408670       1 mutate_app_gateway.go:203] END AppGateway deployment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12b6a17]

goroutine 43 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc000350750, 0xc000591d88, 0xc000f7ea40)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:508 +0x107
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsPodReferencedByAnyIngress(0xc000350750, 0xc001f1ca00, 0xc0020c3c98)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:255 +0x85
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x185e220, 0xc0001e0000, 0xc000046016, 0x24, 0xc000044035, 0xa, 0xc00004400b, 0x13, 0xc00029dce0, 0xc000350750, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:22 +0x384
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0001ef7b0, 0xc0003a07e0, 0xc0003abec0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:39 +0x1fd
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:72 +0x1a8`

* Any Azure support tickets associated with this issue.
NA

**Comment by adamcarter81** [comment]
If I manually attempt to create a front end listener, I can select the certificate 

The rr-80 rule has the correct backend target and http setting - both confusingly referencing the 443/https objects - I would have expected a new rule (say rr-443) to use the relevant objects?

**Comment by adamcarter81** [comment]
After adding the root certificate on the application gateway, this is the error I now receive:

`error: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/probes/pb-istio-system-agic-ingress-https-443-agic-ingress-https protocol (Http) does not match Backend Http Setting /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/backendHttpSettingsCollection/bp-istio-system-agic-ingress-https-443-443-agic-ingress-https protocol (Https)." Details=[]'
I0512 14:40:03.268387       1 mutate_app_gateway.go:187] END AppGateway deployment
E0512 14:40:03.268470       1 controller.go:132] Error mutating App Gateway config from k8s event. network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/probes/pb-istio-system-agic-ingress-https-443-agic-ingress-https protocol (Http) does not match Backend Http Setting /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/backendHttpSettingsCollection/bp-istio-system-agic-ingress-https-443-443-agic-ingress-https protocol (Https)." Details=[]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x122f937]`

**Comment by akshaysngupta** [comment]
@adamcarter81 Can you upgrade the version to `1.2.0-rc1` and see if you still get the error ?
https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.2.0-rc1

**Comment by adamcarter81** [comment]
Ah yes - sorry forgot to add the version - I was using 1.0.0, I upgraded to 1.1.0-rc1, then the latest 1.2.0-rc1 - problem still appears
Status of the pod is CrashLoopBackOff, logs below:
`I0512 16:28:47.567483       1 environment.go:210] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0512 16:28:47.587555       1 main.go:124] App Gateway Details: Subscription: d3af426f-de5c-48ea-a5e8-f645a6ac85e9, Resource Group: rg-aks-lab, Name: ApplicationGateway1
I0512 16:28:47.587934       1 auth.go:46] Creating authorizer from Azure Managed Service Identity
I0512 16:28:47.587759       1 httpserver.go:57] Starting API Server on :8123
I0512 16:28:48.179167       1 main.go:166] Ingress Controller will observe all namespaces.
I0512 16:28:48.334012       1 main.go:194] Unable to associate Application Gateway subnet '/subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/virtualNetworks/aksVirtualNetwork/subnets/appgwsubnet' with route table '/subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/MC_rg-aks-lab_aks-cluster1_westeurope/providers/Microsoft.Network/routeTables/aks-agentpool-35064155-routetable' due to error (this is relevant for AKS clusters using 'Kubenet' network plugin): [network.RouteTablesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'ebe1de66-390d-49b5-b211-bb11afe2529a' with object id 'ebe1de66-390d-49b5-b211-bb11afe2529a' does not have authorization to perform action 'Microsoft.Network/routeTables/read' over scope '/subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/MC_rg-aks-lab_aks-cluster1_westeurope/providers/Microsoft.Network/routeTables/aks-agentpool-35064155-routetable' or the scope is invalid. If access was recently granted, please refresh your credentials."]
I0512 16:28:48.334098       1 context.go:130] k8s context run started
I0512 16:28:48.334129       1 context.go:174] Waiting for initial cache sync
I0512 16:28:48.572161       1 secretstore.go:152] Converted secret [istio-system/wildcard-mintecanalytics-com]
I0512 16:28:49.734272       1 context.go:187] Initial cache sync done
I0512 16:28:49.734545       1 context.go:188] k8s context run finished
I0512 16:28:49.734689       1 worker.go:39] Worker started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x122f937]

goroutine 79 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc0000ee870, 0xc000a0c9d8, 0x1a)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:556 +0x107
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsEndpointReferencedByAnyIngress(0xc0000ee870, 0xc0008d2000, 0xc000152ca8)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:288 +0x11a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x17b5a80, 0xc0001c2900, 0xc000046056, 0x24, 0xc000044075, 0xa, 0xc00004404b, 0x13, 0xc000557980, 0xc0000ee870, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:34 +0x1c3
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0004ea810, 0xc000436960, 0xc0005b3560)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:43 +0x1fc
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:83 +0x1b2`

**Comment by adamcarter81** [comment]
ahhh I just noticed the other error - 403 - Unable to associate Application Gateway subnet, will investigate

**Comment by adamcarter81** [comment]
The error regarding RBAC has now changed to:
`I0512 18:02:00.903000       1 client.go:191] Error getting route table '/subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/MC_rg-aks-lab_aks-cluster1_westeurope/providers/Microsoft.Network/routeTables/aks-agentpool-35064155-routetable' (this is relevant for AKS clusters using 'Kubenet' network plugin): network.RouteTablesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/routeTables/aks-agentpool-35064155-routetable' under resource group 'MC_rg-aks-lab_aks-cluster1_westeurope' was not found."`


The error related to the probe protocol mismatch still persists:
`error: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/probes/pb-istio-system-agic-ingress-https-443-agic-ingress-https protocol (Http) does not match Backend Http Setting /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/backendHttpSettingsCollection/bp-istio-system-agic-ingress-https-443-443-agic-ingress-https protocol (Https)." Details=[]'
I0512 18:02:04.270020       1 mutate_app_gateway.go:187] END AppGateway deployment
E0512 18:02:04.270039       1 controller.go:132] Error mutating App Gateway config from k8s event. network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/probes/pb-istio-system-agic-ingress-https-443-agic-ingress-https protocol (Http) does not match Backend Http Setting /subscriptions/d3af426f-de5c-48ea-a5e8-f645a6ac85e9/resourceGroups/rg-aks-lab/providers/Microsoft.Network/applicationGateways/ApplicationGateway1/backendHttpSettingsCollection/bp-istio-system-agic-ingress-https-443-443-agic-ingress-https protocol (Https)." Details=[]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x122f937]

goroutine 125 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc0001a0ea0, 0xc00041db90, 0xc002379390)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:556 +0x107
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsPodReferencedByAnyIngress(0xc0001a0ea0, 0xc000f69480, 0xc001061ca8)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:277 +0x85
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x17b5a80, 0xc00014a900, 0xc000046016, 0x24, 0xc000044035, 0xa, 0xc00004400b, 0x13, 0xc0000dd770, 0xc0001a0ea0, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:23 +0x719
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0004ada40, 0xc0003b0180, 0xc00010fe00)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:43 +0x1fc
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:83 +0x1b2`

**Comment by 3quanfeng** [comment]
Hi @adamcarter81, it's an identified bug, the fix has been committed to master, will be available in 1.2.0-rc2

**Comment by adamcarter81** [comment]
> Hi @adamcarter81, it's an identified bug, the fix has been committed to master, will be available in 1.2.0-rc2

Thanks - is there any ETA for rc2?

**Comment by wshaikh16** [comment]
I am still seeing "protocol (Http) does not match Backend Http Setting (Https)" is this issue resolved?

**Comment by akshaysngupta** [comment]
@wshaikh16 Is the probe protocol coming from the readiness probe ?

**Comment by wshaikh16** [comment]
When trying to create the HTTP settings for protocol https.

I0120 15:12:21.821112       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment                                                                                                                                                                                         │
│ I0120 15:12:22.045055       1 mutate_app_gateway.go:183] END AppGateway deployment                                                                                                                                                                                           │
│ E0120 15:12:22.045182       1 controller.go:141] network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /subscriptions/resourceGroups/s00020nrgp04c3polab-network/providers/Microsoft.Network/applicationGateways/s00020nappgtwy04c3polab/probes/pb-istio-system-istio-ingressgateway-443-nginxhttps-ingress protocol (Http) does not match Backend Http Setting /su │
│ bscriptions/resourceGroups/s00020nrgp04c3polab-network/providers/Microsoft.Network/applicationGateways/s00020nappgtwy04c3polab/backendHttpSettingsCollection/bp-istio-system-istio-ingressgateway-443-8443-nginxhttps-ingress protocol  │
│ (Https)." Details=[]                                                                                                                                                                                                                                                         │
│ E0120 15:12:22.045214       1 worker.go:62] Error processing event.network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /su │
│ bscriptions/8522fc74-159a-4112-af66-64481a8bb68f/resourceGroups/s00020nrgp04c3polab-network/providers/Microsoft.Network/applicationGateways/s00020nappgtwy04c3polab/probes/pb-istio-system-istio-ingressgateway-443-nginxhttps-ingress protocol (Http) does not match Backen │
│ d Http Setting /subscriptions/8522fc74-159a-4112-af66-64481a8bb68f/resourceGroups/s00020nrgp04c3polab-network/providers/Microsoft.Network/applicationGateways/s00020nappgtwy04c3polab/backendHttpSettingsCollection/bp-istio-system-istio-ingressgateway-443-8443-nginxhttps │
│ -ingress protocol (Https)." Details=[]                                                                                                                                                                                                                                       │
│ I0120 15:12:22.045295       1 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"ingress-appgw-deployment-568fb7d4-r7z6x", UID:"60dd7e9a-82f2-4ffc-9a36-07973b04f23d", APIVersion:"v1", ResourceVersion:"7879844", FieldPath:""}): type: 'War │
│ ning' reason: 'FailedApplyingAppGwConfig' network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeProtocolMustMatchBackendHttpSettinsProtocol" Message="Probe /subscriptions/resourceGroups/s00020nrgp04c3polab-network/providers/Microsoft.Network/applicationGateways/s00020nappgtwy04c3polab/probes/pb-istio-system-istio-ingressgateway-443-nginxhttps-ingress protocol (Http) does not match Backend Http Setting /subscript │
│ ions/resourceGroups/s00020nrgp04c3polab-network/providers/Microsoft.Network/applicationGateways/s00020nappgtwy04c3polab/backendHttpSettingsCollection/bp-istio-system-istio-ingressgateway-443-8443-nginxhttps-ingress protocol (Https) │
│ ." Details=[]
